### ISSUE TITLE
Can we use the word2vec model in training?

### ISSUE THREAD

**Issue by wangs311** [VIPriors/vipriors-challenges-toolkit#11]
Hello,

I am interested in VIPriors challenge. I am curious to know if I can use the word2vec model in training?

Looking forward to your reply!

**Comment by rjbruin** [comment]
Thanks for your interest in the challenges!

Word2vec is an interesting edge case of the rules, so this is a good question. However, we must apply the rules consistently:

- You cannot use any pre-trained word2vec models or embeddings.
- You *can* however use the word2vec method, by training embeddings yourself, but only on the provided data.

I hope that answers your question.

**Comment by wangs311** [comment]
Thanks for your reply!
