### ISSUE TITLE
Submission error in development phase for ReID challenge

### ISSUE THREAD

**Issue by fukaf** [VIPriors/vipriors-challenges-toolkit#12]
Hi, I got an error after submitting and running in the development phase.

Here is the error output:

'''
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/opt/conda/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

'''

and the mAP outputs 'nan'.

I am wondering if this is caused by the submitted file or the platform?

BTW, the .csv file seems alright with 51 rows and 911 cols which generated using code from provided baseline.py.

Best

**Comment by dzambrano** [comment]
Hello, could you try again? 
The reference file was not correct and now it works on my side.
If eventually you still encounter problems, would you mind sending me your .csv file so I can make a few tests myself?

Thanks

**Comment by fukaf** [comment]
It seems alright now. Thanks.
