### ISSUE TITLE
Occluded labels

### ISSUE THREAD

**Issue by Zhang-HM** [VIPriors/vipriors-challenges-toolkit#14]
Hello,

I am interested in 2021 VIPriors Object Detection Challenge.

I have a question, there are four possible states(intact, damaged, absent and occluded). In you paper, the missing parts(absent, occluded) are not used during training nor testing, but the occluded is used during training in your code?
[bike_dataset.py](https://github.com/VIPriors/vipriors-challenges-toolkit/blob/master/object-detection/dataset/bike_dataset.py)

```
for ind,i in enumerate(labels['parts'],0):
      lab = labels['parts'][i]
      if  lab['object_state'] != 'absent':
          loc = lab['absolute_bounding_box']
          xmin = loc['left']
          xmax = loc['left'] + loc['width']
          ymin = loc['top']
          ymax = loc['top'] + loc['height']
          boxes.append([xmin, ymin, xmax, ymax])
          labs.append(ind+1)

```
Are the occluded labels used in the test set?

**Comment by oskyhn** [comment]
Hello Zhang,

Thanks for the question. In the paper, we focus on the problem from visual verification perspective. For the challenge, we look at the problem from object detection aspect, therefore we include **occluded** parts for both **training** and the **evaluation**.
