### ISSUE TITLE
How to form a team for this competition？

### ISSUE THREAD

**Issue by Wprofessor** [VIPriors/vipriors-challenges-toolkit#16]
Hello，
I want to know how to form a team for this competition？
Let me know soon.
-Jiahao Wang

**Comment by rjbruin** [comment]
Hi Jiahao,

You can find all information on our website: https://vipriors.github.io/challenges/
Then you can enroll to the competition on the CodaLab page of the respective challenge you wish to participate in.

Hope that helps!

**Comment by wanghao15536870732** [comment]
> Hi Jiahao,
> 
> You can find all information on our website: https://vipriors.github.io/challenges/
> Then you can enroll to the competition on the CodaLab page of the respective challenge you wish to participate in.
> 
> Hope that helps!

Hi, Jiahao Wang and I are from a team, we are participating in VIPriors VIPriors Image Classification Challenge and just submitted today, but the leaderboard shows our own registered name, not our team name, is this correct?

**Comment by rjbruin** [comment]
Yes, that is correct. Submissions from separate team members will show separately on the leaderboard. After the submission phase ends, we will merge submissions from users in the same team.

However, I do see that only @Wprofessor has subscribed to the CodaLab competition with a team name. I'd suggest that @wanghao15536870732 would do the same thing, if you can edit this. If not, that is not a problem.

Also, please keep in mind that the leaderboard on CodaLab is not final, as only teams that submit a technical report will qualify. We will publish the final leaderboards on the workshop website after reviewing the tech reports.

**Comment by wanghao15536870732** [comment]
> Yes, that is correct. Submissions from separate team members will show separately on the leaderboard. After the submission phase ends, we will merge submissions from users in the same team.
> 
> However, I do see that only @Wprofessor has subscribed to the CodaLab competition with a team name. I'd suggest that @wanghao15536870732 would do the same thing, if you can edit this. If not, that is not a problem.
> 
> Also, please keep in mind that the leaderboard on CodaLab is not final, as only teams that submit a technical report will qualify. We will publish the final leaderboards on the workshop website after reviewing the tech reports.

I understand, thank you very much.

**Comment by wanghao15536870732** [comment]
Hello organizers! I'd like to confirm that the maximum number of submissions is 20, is it 20 for each member of the group?

**Comment by rjbruin** [comment]
As far as I know, the maximum should be 20 per CodaLab user (10 for the action recognition challenge). Ideally, we would limit teams to 20 submissions as well, but there seems to be no way that we can make this restriction apply to teams instead of individual users in CodaLab, so teams have a small advantage in this regard.
