### ISSUE TITLE
Failed to upload file

### ISSUE THREAD

**Issue by Zhang-HM** [VIPriors/vipriors-challenges-toolkit#22]
Hello, falied to upload the result file!

**Comment by Zhang-HM** [comment]
![屏幕快照 2021-08-30 下午11 32 00 上午](https://user-images.githubusercontent.com/22315477/131281281-97f1cb57-bb36-4453-a495-8ecbb6a65e3c.png)

**Comment by rjbruin** [comment]
Codalab is having technical issues, currently. Sorry! We will let you know once these are fixed.

**Comment by LcenArthas** [comment]
Hi Robert-Jan,

I have the same problem, failed to upload the result file and this has been going on for two days.

**Comment by rjbruin** [comment]
The CodaLab issues appear to have been fixed, so this problem should be resolved.
