### ISSUE TITLE
instance seg, submitting failed: docker: write /var/lib/docker/tmp/GetImageBlob487409347: no space left on device.

### ISSUE THREAD

**Issue by YJingyu** [VIPriors/vipriors-challenges-toolkit#24]
hi @rjbruin I submit results to val and test set, get the same error like this, but I can get the val set result offline by toolkit you provided. help me, thanks

Unable to find image 'rjbruin/vipriors-object-detection-evaluation:1.1' locally
1.1: Pulling from rjbruin/vipriors-object-detection-evaluation
4ae16bd47783: Pulling fs layer
46d3909aefd6: Pulling fs layer
b8fd74fabe0f: Pulling fs layer
836d375308d1: Pulling fs layer
338996cb2698: Pulling fs layer
f98d8d5f66de: Pulling fs layer
7d209ed0cc7b: Pulling fs layer
190e5781d107: Pulling fs layer
0499accd4745: Pulling fs layer
d9aa9a503246: Pulling fs layer
77f2dbd77c97: Pulling fs layer
7d209ed0cc7b: Waiting
190e5781d107: Waiting
0499accd4745: Waiting
d9aa9a503246: Waiting
77f2dbd77c97: Waiting
836d375308d1: Waiting
338996cb2698: Waiting
f98d8d5f66de: Waiting
46d3909aefd6: Download complete
4ae16bd47783: Verifying Checksum
4ae16bd47783: Download complete
836d375308d1: Verifying Checksum
836d375308d1: Download complete
f98d8d5f66de: Verifying Checksum
f98d8d5f66de: Download complete
4ae16bd47783: Pull complete
338996cb2698: Verifying Checksum
338996cb2698: Download complete
190e5781d107: Verifying Checksum
190e5781d107: Download complete
7d209ed0cc7b: Verifying Checksum
7d209ed0cc7b: Download complete
0499accd4745: Verifying Checksum
0499accd4745: Download complete
d9aa9a503246: Verifying Checksum
d9aa9a503246: Download complete
docker: write /var/lib/docker/tmp/GetImageBlob487409347: no space left on device.
See 'docker run --help'.

**Comment by rjbruin** [comment]
I've made the CodaLab people aware of this, as they would need to fix this.

**Comment by YJingyu** [comment]
> I've made the CodaLab people aware of this, as they would need to fix this.

Thanks a lot, hope can fix it as soon

**Comment by rjbruin** [comment]
Hi @YJingyu, can you confirm if this issue is still present?

**Comment by YJingyu** [comment]
> Hi @YJingyu, can you confirm if this issue is still present?

Hi, this happened again today, but about 1 hour later, for same submission it is ok, I am a little confused. This error leads to some failed submissions, Could you consider to increase some submissions per day and total properly?

![image](https://user-images.githubusercontent.com/22312719/133767288-3127bd4f-1dcf-48ca-98ac-1d7de705e531.png)

**Comment by rjbruin** [comment]
Thanks for the quick response. I've opened a new issue with the Codalab maintainers: https://github.com/codalab/codalab-competitions/issues/2996

I'm hoping they will respond quickly.

**Comment by YJingyu** [comment]
> Thanks for the quick response. I've opened a new issue with the Codalab maintainers: [codalab/codalab-competitions#2996](https://github.com/codalab/codalab-competitions/issues/2996)
> 
> I'm hoping they will respond quickly.

Many thanks.

**Comment by YJingyu** [comment]
> Thanks for the quick response. I've opened a new issue with the Codalab maintainers: [codalab/codalab-competitions#2996](https://github.com/codalab/codalab-competitions/issues/2996)
> 
> I'm hoping they will respond quickly.

Hi, this happended again today.
![image](https://user-images.githubusercontent.com/22312719/133880204-1c5a8b76-a44a-474c-9e68-95c1058afc54.png)
