### ISSUE TITLE
GAN-based Annotation with other data

### ISSUE THREAD

**Issue by anamozov** [VIPriors/vipriors-challenges-toolkit#25]
I know that using a pre-trained network with additional data is not allowed for training the detection model. 
But I want to specify whether we can use GAN models that have been pre-trained with other than challenge data for **only data augmentation**? 
Thanks.

**Comment by rjbruin** [comment]
Hi! Thanks for your interest in our challenges!

No, using any kind of external model is not allowed, as that model is trained on external data.
