### ISSUE TITLE
can't upload the results in re-id track.

### ISSUE THREAD

**Issue by qiguming** [VIPriors/vipriors-challenges-toolkit#26]
"Sorry, failed to upload file."

**Comment by rjbruin** [comment]
Hi qiguming, do you have a more extensive error message to share?

**Comment by qiguming** [comment]
> Hi qiguming, do you have a more extensive error message to share?

![image](https://user-images.githubusercontent.com/31810368/131812765-f9239259-1b9a-4c5f-9c81-389b8f1ff1f2.png)
No more error message

**Comment by rjbruin** [comment]
This is very likely related to this CodaLab issue: https://github.com/codalab/codalab-competitions/issues/2983

I'm hoping for the CodaLab admins to fix it. In the meantime, perhaps you can keep trying to submit.
