### ISSUE TITLE
Kinetics400ViPriors Download extremely slow

### ISSUE THREAD

**Issue by 0russ** [VIPriors/vipriors-challenges-toolkit#27]
Hi @rjbruin, I am a student from China and I am very interested in the 2021 VIPriors Action Recognition Challenge. But I am suffering from an extremely slow download speed (10kb/s) when I am trying to download the datasets from the SURF Drive. I would really appreciate it if you can provide another download link such as Google Cloud or BaiDu Cloud , Thanks a lot!

**Comment by rjbruin** [comment]
Hi @0russ, unfortunately we cannot arrange this hosting the dataset elsewhere, at least not in any kind of short time frame.

Your download speed seems way too low to me, however. You could try sending an email to the SURFDrive helpdesk, to see if there is something that they could help with. Their email address is helpdesk@surfsara.nl.

**Comment by 0russ** [comment]
Thanks for your kind reply, I came up with another solution. I have got the original Kinetics400 dataset, which means that I have all the *mp4 files, so all I need are the annotation files in your dataset. I wonder if you can provide me with the annotation files solely. Without the video files in Kinetics400ViPriors, it would be much easier for me to download.

**Comment by rjbruin** [comment]
Unfortunately that won't work, since we scrambled the annotations of the original dataset in creating ours. We did this to make it harder to cheat on the challenge by secretly training on the original full-size dataset. Sorry!

**Comment by 0russ** [comment]
OK, thanks for your reply!

**Comment by rjbruin** [comment]
We've had more complaints about the download speeds, so we're going to try to find another solution. @0russ, can you try if this download from Google Drive works better? See the link below. It's only part of the dataset, but if this works better we may find a solution by spreading the dataset over multiple Drive accounts, to avoid storage limits.

https://drive.google.com/drive/folders/1ynqDSEqEN88zoNKR32OaFQXggFOAj-UY?usp=sharing

**Comment by 0russ** [comment]
Thanks a lot! Google Drive is much more faster (6 MB/s)
![image](https://user-images.githubusercontent.com/54385993/132683154-eaa43e99-deb7-47aa-bb78-2f5c83ecc9e6.png)

**Comment by WuJie1010** [comment]
can you provide all datas in google drive?

**Comment by rjbruin** [comment]
We're working on it!

**Comment by rjbruin** [comment]
The full dataset is now available through the same link. :)
