### ISSUE TITLE
for action recognition dataset

### ISSUE THREAD

**Issue by WuJie1010** [VIPriors/vipriors-challenges-toolkit#32]
Can you direct provide kinetics400ViPriors-val.csv/kinetics400ViPriors-train.csv/kinetics400ViPriors-test.csv for us?

**Comment by WuJie1010** [comment]
annotations/clsInd.csv: class label and index.
annotations/kinetics400ViPriors-train.csv: annotated ground truth of the training videos.
annotations/kinetics400ViPriors-val.csv: annotated ground truth of the validation videos.
annotations/kinetics400ViPriors-test-public.csv: test videos, without annotations.

These files~

**Comment by rjbruin** [comment]
Unfortunately, that wouldn't help as the dataset was scrambled. See #27.

**Comment by rjbruin** [comment]
See #27 for the link to the full dataset.

**Comment by alisher-ai** [comment]
Hi, I am confused. Have not you already provided the annotation files here: https://github.com/VIPriors/vipriors-challenges-toolkit/tree/master/action-recognition/data/annotations ?

**Comment by bapmbr** [comment]
We are sorry. Maybe some clarification is needed here.

As we mentioned [here](https://github.com/VIPriors/vipriors-challenges-toolkit/tree/master/action-recognition/data), **the Action Recognition challenge uses a modification of the Kinetics400 dataset**, which can be downloaded from this link: https://drive.google.com/drive/folders/1ynqDSEqEN88zoNKR32OaFQXggFOAj-UY?usp=sharing.

This means that although videos are from the original dataset, we have modified it in such a way that video names and their distribution across the splits are completely different from the original.

The annotations we provide in this [link](https://github.com/VIPriors/vipriors-challenges-toolkit/tree/master/action-recognition/data/annotations) are those of the modified dataset (the one used in the challenge). So, it is not possible to build the modified dataset from the original one using those annotations, as the names of the videos do not match.

This is why we directly provide a link to download the dataset.
