### ISSUE TITLE
Submission not on leaderboard

### ISSUE THREAD

**Issue by keloee** [VIPriors/vipriors-challenges-toolkit#33]
I made two submissons of the Instance seg challenge, but I don't find myself on leaderboard. Is there something that I did wrong or something else?

**Comment by rjbruin** [comment]
What is your CodaLab username? Then I can inspect the submissions.

Generally though you need to select a submission for publication to the leaderboard. That doesn't happen automatically.

**Comment by keloee** [comment]
Thanks for the heads up, I just saw the button "submit to leaderboard"
