### ISSUE TITLE
Submission Error occured in instance segmentation, can you fix it?

### ISSUE THREAD

**Issue by YJingyu** [VIPriors/vipriors-challenges-toolkit#34]
@Attila94 @rjbruin 
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpZy6Ah4/run/program/evaluate.py", line 82, in 
    evaluate_from_files(args[0], args[1], args[2])
  File "/tmp/codalab/tmpZy6Ah4/run/program/evaluate.py", line 45, in evaluate_from_files
    with open(groundtruths_filepath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpZy6Ah4/run/input/ref/groundtruths.json'

And also I did not  submit anything  in 09/15/2021 12:57, but there are some failed submissions, I am confused, the details are attached. help me,  thanks.
<img width="812" alt="截屏2021-09-15 下午10 03 35" src="https://user-images.githubusercontent.com/22312719/133448759-ce149512-a37a-49f1-8b74-6186eff0e182.png">

**Comment by rjbruin** [comment]
@Attila94 Seems like something is wrong with the new dataset version? No `groundtruths.json`?

**Comment by YJingyu** [comment]
> @Attila94 Seems like something is wrong with the new dataset version? No `groundtruths.json`?
I think so, this error occured after recevied your email

**Comment by Attila94** [comment]
Should be fixed now, can you please check? :)

**Comment by YJingyu** [comment]
> Should be fixed now, can you please check? :)

Yes, fixed, thanks very much! but it is regrettable that this error caused some invalid submissions.

**Comment by YJingyu** [comment]
> Should be fixed now, can you please check? :)

Maybe there is a another error in new dataset version, the score of [AP @ 0.50:0.95 (small) ] is too small, it is strange, the val result I calculate offline is 0.3.., but the result in submission board is 0.0.. And also I see in old dataset version the result is ok, but in new dataset version, I think there are maybe some mistakes, can you check it?
<img width="942" alt="截屏2021-09-16 上午10 34 20" src="https://user-images.githubusercontent.com/22312719/133540086-dae64bd6-1f8c-45fe-aa46-47c2d7f07332.png">

**Comment by Attila94** [comment]
> > Should be fixed now, can you please check? :)
> 
> Yes, fixed, thanks very much! but it is regrettable that this error caused some invalid submissions.

I've deleted your failed submissions so these will not be included in your submission count anymore. I'll look into the other issue now.
