### ISSUE TITLE
Maybe there is a error in new instance segmentation dataset version, can you check it?

### ISSUE THREAD

**Issue by YJingyu** [VIPriors/vipriors-challenges-toolkit#35]
@rjbruin @Attila94 
The score of [AP @ 0.50:0.95 (small) ] is too small, it is strange, the val result I calculate offline is 0.3.., but the result in submission board is 0.0.. And also I see in old dataset version the result is ok, but in new dataset version, I think there are maybe some mistakes, this result is likely the score of bbox, can you check it?
<img width="942" alt="截屏2021-09-16 上午10 34 20的副本" src="https://user-images.githubusercontent.com/22312719/133645496-80976608-c731-43c2-9bf7-6a43d31a2083.png">

**Comment by Attila94** [comment]
We corrected and checked all labels in the new version of the dataset so there should be no issue there. I've rerun the evaluation of your submission locally and got the same metrics as the online eval. Are you sure you are using the new dataset version for training and local evaluation?

**Comment by YJingyu** [comment]
> We corrected and checked all labels in the new version of the dataset so there should be no issue there. I've rerun the evaluation of your submission locally and got the same metrics as the online eval. Are you sure you are using the new dataset version for training and local evaluation?

A you mentioned in #31 [The new labels are also uploaded to the evaluation server although this issue should not affect any scores as bounding boxes are not used for evaluation], so  I take the local evaluation in old dataset version, I will evaluate in new and feedback to you, thanks.

**Comment by YJingyu** [comment]
> We corrected and checked all labels in the new version of the dataset so there should be no issue there. I've rerun the evaluation of your submission locally and got the same metrics as the online eval. Are you sure you are using the new dataset version for training and local evaluation?

I verified, the result is true in new dataset, thanks for your reply and check, I will close this issue

**Comment by Attila94** [comment]
Thanks for checking!
