### ISSUE TITLE
Final submit issue

### ISSUE THREAD

**Issue by keloee** [VIPriors/vipriors-challenges-toolkit#40]
Dear organizeer I have a few questions. 1. Do our final result have to be on leaderboard? 2. As described in https://vipriors.github.io/ All deadlines are 23:59 GMT. But the CodaLab phase ended 22:59 GMT. Due to this two question our best result do not apear on the leaderboard, is this matter and is there anything you or I can do?

**Comment by rjbruin** [comment]
1. Yes, your final result should be on the leaderboard. If you submitted it before the deadline, but have not published the result to the leaderboards (as can be done by the button on the submission page), please do so now.
2. Indeed, the website listed a different time than the Codalab server. If you didn't submit in time before the server closed, we are sorry to cause these issues. We are currently looking into a way to accommodate participants with this issue. Please stay tuned as we figure this out.

**Comment by keloee** [comment]
The problem is I can no longer submit my result to the leaderboard. It seems the button has disappeared for the test phase has ended

**Comment by rjbruin** [comment]
We are aware. We're looking into it. Please stay tuned.

**Comment by rjbruin** [comment]
See the official email and the final response to #43.
