### ISSUE TITLE
Questions about the VIPriors Target Detection Challenge rankings for 2021.

### ISSUE THREAD

**Issue by Zhang-HM** [VIPriors/vipriors-challenges-toolkit#41]
Hello, I am very interested in this competition, but the result of the first place on the leaderboard looks not very reasonable, it is more like the result of manual labeling, please check it.

**Comment by rjbruin** [comment]
Please note that the current Codalab leaderboard is not the final leaderboard. All competitors will be required to submit a technical report. If this report is not submitted by the same email address as submitted the entry on the leaderboard, then the entry does not qualify for the final leaderboard. If the technical report does not seem to match with the results on the leaderboard, we reserve the right to disqualify the entry. This includes if we suspect the entry to be the result of cheating.
