### ISSUE TITLE
Query about The Re-submission

### ISSUE THREAD

**Issue by longmao-yiran** [VIPriors/vipriors-challenges-toolkit#43]
The re-submission site should be open for those who did not submit their final results due to the unclarities about the submission deadline (only one hour deviation). Those who had submitted their results in Sept. 24th should not re-submitted again, since there is just one submission opportunity one day. Otherwise, this may provide a cheating chance for someone.

I want to take an example in the track of "image classification". The team "Wprofessor" had submitted his result in Sept. 24th, and the top-1 accuracy is only about 72%. He had already used his opportunity for submission in the deadline of Sept. 24th. Due to the extension of deadline to Sept. 28th which is provided for those who did not submit their results in Sept. 24th, "Wprofessor" re-submitted again in Sept. 27th and increased his result from 72% to 75% by a large margin in only a few days (This track is of high resource-consuming which requires hundreds of GPU-day at least). This is ridiculous, unfair and unacceptable.

<img width="579" alt="1" src="https://user-images.githubusercontent.com/9360593/135015579-3ea1aa2d-120b-439a-9256-08d197c26757.png">
<img width="561" alt="2" src="https://user-images.githubusercontent.com/9360593/135015585-1b8de568-fb5e-4326-b7ea-7485d7013bf0.png">

**Comment by RojunLin** [comment]
I agree with you, and hope someone can give a convincing reply.

**Comment by rjbruin** [comment]
Please give us some time to consider your comments. We are trying our best to host a fair and open competition using the means at our disposal. We will get back to you shortly.

**Comment by longmao-yiran** [comment]
@rjbruin I very appreciate your effort to host such meaningful competitions, and I understand the reason to give another chance for a few participants who miss the submission deadline (Sept. 24th). But it is forbidden and unacceptable to re-submit again for those who had already submitted his result in the deadline of Sept. 24th (one submission opportunity one day). Also, I want to give a suggestion that the participants should be required to release their source code in github along with their tech reports. This is beneficial for validating the reproducibility and building strong baselines for the community of VIPriors.

**Comment by YJingyu** [comment]
> @rjbruin I very appreciate your effort to host such meaningful competitions, and I understand the reason to give another chance for a few participants who miss the submission deadline (Sept. 24th). But it is forbidden and unacceptable to re-submit again for those who had already submitted his result in the deadline of Sept. 24th (one submission opportunity one day). Also, I want to give a suggestion that the participants should be required to release their source code in github along with their tech reports. This is beneficial for validating the reproducibility and building strong baselines for the community of VIPriors.

For those who had already submitted his result in the deadline of Sept. 24th (one submission opportunity one day), they can sign up with another email address and get a new account, so that they can become the people who miss the submission deadline (Sept. 24th), they can submit again. Ultimately, they open the submission path again is unfair, there are many factors can influence the final result.

**Comment by Zhang-HM** [comment]
Yes, I think so, too. Resubmission, resulting in three unfair issues, new accounts, cheating, and longer model training time (September 25 to September 27), which is difficult to distinguish. For example, for the new account, the account registered long ago can be used to submit the result, and the result was not submitted on September 24, so the result can be greatly improved. These problems are caused by resubmission.

**Comment by Wprofessor** [comment]
I know you may be a little skeptical about our results, and we will upload our technical reports and code on GitHub after the competition is officially over.

**Comment by Michael-sys236** [comment]
> I know you may be a little skeptical about our results, and we will upload our technical reports and code on GitHub after the competition is officially over.

This is not the point. You had already submitted your result in September 24.  You had no chance to resubmit again after the deadline, no matter how you achieved your result. This is the rule.
