### ISSUE TITLE
unfair competition and terrible experience！we need more compelling  reply

### ISSUE THREAD

**Issue by YJingyu** [VIPriors/vipriors-challenges-toolkit#44]
@rjbruin @Attila94 Suddenly  we received a email“extend the deadline until Wednesday, September 29th, 2021, 23:59 UTC”,  originally deadline is Sept. 24th 2021, 11 p.m. UTC, we  received the email at Sept. 26th 2021, 10:10 a.m. UTC, there are two day intervals. For the person who want to delay the deadline, they have enough time to train and improve the model, but most of us didn’t know the deadline will be delayed, we did nothing these two days, but they can, I think this is a cheating time.

And latter you send email again，the deadline updated “Sept 28, 01:59 AM UTC”, I think this is a more terrible decision, most of us who received the last email at 26th 2021, 10:10 a.m. UTC and know the new deadline, we have some time to improve our model, but you change the deadline again, for the competitors who received the last email at 26th 2021, 10:10 a.m. UTC and know the new deadline is “September 29th, 2021, 23:59 UTC” are unfair, they don’t have enough time to train new model, but for the person who want to delay the deadline, they not only can improve their model during Sept. 24th 2021, 11 p.m. UTC to Sept.  26th 2021, 10:10 a.m. UTC, but also can prevent other competitors to improve their model because of the time limit. I think you should consider seriously whether it is fair or not, because most of us known the deadline is Sept. 24th 2021, 11 p.m. UTC, it is clear on homepage, just few competitors, maybe they hidden their score results on purpose, so finally maybe forget to submit the result to board, I think this their own reasons, they do this just want to win the competition  maliciously，because they know other competitors‘ result， but other competitors do not know their result. For a study competition,  this is a bad direction, I think the purpose that you hold this competition is not this. But you changed the deadline again and again which aggravates the bad direction.

By the way, I see the results in Instance Segmentation, the 2nd and 3rd have same score result for every evaluation index, and for 2nd he just submit only once then get a high score same with 3rd， so I doubt  they might have cheated，and I think they are new competitors after the deadline 24th 2021, 11 p.m. UTC, so these two results are valid ？
<img width="1115" alt="截屏2021-09-28 上午11 30 03" src="https://user-images.githubusercontent.com/22312719/135026585-4016daeb-2d1c-492e-9a37-394435604cee.png">

**Comment by YJingyu** [comment]
@rjbruin @Attila94  We are waiting for your reply always.

**Comment by rjbruin** [comment]
The final results of the challenge are listed on the challenge website: https://vipriors.github.io/challenges. Only challenge entries accompanied by a technical report qualified for the final rankings.

In response to concerns raised about the extension of the submission deadline, we have decided to merge the leaderboards at the time of the original deadline and at the time of the extended deadline. This means that all competitors will place at the rank that is highest between the two deadlines, and there are shared ranks.
