### ISSUE TITLE
 I doubt they might have cheated in Instance Segmentation Challenge, please check it

### ISSUE THREAD

**Issue by YJingyu** [VIPriors/vipriors-challenges-toolkit#45]
@rjbruin @Attila94 I see the results in Instance Segmentation, the 2nd and 3rd have same score result for every evaluation index, and for 2nd they just submit only once then get a high score same with 3rd， so I doubt  they might have cheated，and I think they are new competitors after the deadline 24th 2021, 11 p.m. UTC, so these two results are valid ？
<img width="1115" alt="截屏2021-09-28 上午11 30 03" src="https://user-images.githubusercontent.com/22312719/135026724-9d097612-8859-4bfd-96c6-694d99bb88ea.png">

**Comment by Zhang-HM** [comment]
It is not fair for most teams to reopen the competition, because some teams may train a better model between 25th and 27th, it is not reasonable for the leadboard of all competitions to change drastically within 9 hours.
