### ISSUE TITLE
Unfair and extremely bad racing experience

### ISSUE THREAD

**Issue by Zhang-HM** [VIPriors/vipriors-challenges-toolkit#46]
First of all, the reason for reopening the competition is unacceptable. Everyone can see the deadline of the competition on the competition page. Regarding the issue of the time difference between https://vipriors.github.io/ and CodaLab, no contestant raised objections to the organizer. I think everyone should use the time on CodaLab as the deadline, or accept different deadlines, and everyone will use the time on CodaLab as the deadline because it ends sooner. 

And most players submit their scores a few hours or days before the deadline, but some players choose not to make it public. In my opinion, the main reason is that these players did not disclose their results before the deadline, so why reopen the competition submission? Isn’t it enough to provide them with a way to submit their results to board? Therefore, it is not necessary to reopen the competition submission channel.

![24th leadboard](https://user-images.githubusercontent.com/22315477/135036350-8a36338c-68fb-452c-8eca-2c4e4ef2d8ef.png)

<img width="1116" alt="28_leadboard" src="https://user-images.githubusercontent.com/22315477/135037423-8bc3d887-27aa-4842-a20d-78caf64ccbe6.png">

Secondly, we discuss the fairness of the competition. In the object detection competition, scores barely improved in the days leading up to the deadline. And now the 2th  player improved his scores to second place in just 9 hours, which is very incredible, and the **2th** player only ranked **18th** on the **24th** leadboard. I suspect that he retrained a better model in a few days from the 25th to the 27th or adopts other methods. Is it fair to submit the model results trained from the 25th to the 27th? And most of contestants think that the competition is over. Is there some contestants who think they can resubmit their results through feedback to the organizer, so as to improve the performance of their models between the 25th and the 27th?

Finally, I recommend using the initial leadboard as the final result of the competition. There are too many unfair factors in it, and using the initial leadboard is fair to all contestants.

There are also the same unfair problems in other competition, such as Instance Segmentation.

**Comment by YJingyu** [comment]
I agree with your idea, we need more compelling  reply,  otherwise whether we can feedback this serious problem to ICCV chair?

**Comment by jinxuan777** [comment]
Since there are no rules for the limitation of pre-training models. Some teams achieved a higher score with a stronger pre-trained models, such as models trained on objects365. Finally, there is three champion teams awarded in the 2019 COCO competition instance segmentation track. Maybe it is a way to deal with the unfairness.

**Comment by rjbruin** [comment]
Please be assured we are listening to your concerns. We are a small team of publicly funded PhD candidates doing our best to host a competition that is fair and accommodates all competitors. 

On the issue of the submission deadline, we will again consider your concerns and hope to address them soon. 

As for cheating, we have already repeatedly said that any suspecious submissions will be investigated after the tech report deadline this Friday. At this point it is not necessary anymore to report these submissions.

**Comment by rjbruin** [comment]
> Since there are no rules for the limitation of pre-training models. Some teams achieved a higher score with a stronger pre-trained models, such as models trained on objects365. Finally, there is three champion teams awarded in the 2019 COCO competition instance segmentation track. Maybe it is a way to deal with the unfairness.

Could you explain what you mean when you say there are "no rules about pre-training models"?

**Comment by jinxuan777** [comment]
> > Since there are no rules for the limitation of pre-training models. Some teams achieved a higher score with a stronger pre-trained models, such as models trained on objects365. Finally, there is three champion teams awarded in the 2019 COCO competition instance segmentation track. Maybe it is a way to deal with the unfairness.
> 
> Could you explain what you mean when you say there are "no rules about pre-training models"?

COCO allowed additional data for pretrained model. In 2015-2018 all teams used ImageNet as additional labeled data. But in 2019 some teams got higher scores with objects365 and Imagenet as additional data. Finally the teams that got a mAP higher than 0.5 achieve champion.
![image](https://user-images.githubusercontent.com/23650957/135067761-363727a9-b0f0-42b5-93d8-065a404e6773.png)

**Comment by jinxuan777** [comment]
![image](https://user-images.githubusercontent.com/23650957/135068598-a7f000f5-8310-4270-9f6c-d5d556ecdff9.png)
just show the case

**Comment by jvgemert** [comment]
Hi all,

Thank you very much for your detailed analysis. 
We understand these concerns, and really appreciate your efforts in participating in the competition and also in doing this analysis. 

We will deliberate internally how to handle these issues to make sure we arrive at a fair solution.

Best, 

Jan

**Comment by Zhang-HM** [comment]
We have been waiting for your reply!

**Comment by rjbruin** [comment]
The final results of the challenge are listed on the challenge website: https://vipriors.github.io/challenges. Only challenge entries accompanied by a technical report qualified for the final rankings.

In response to concerns raised about the extension of the submission deadline, we have decided to merge the leaderboards at the time of the original deadline and at the time of the extended deadline. This means that all competitors will place at the rank that is highest between the two deadlines, and there are shared ranks.
