### ISSUE TITLE
Question about technical report ddl

### ISSUE THREAD

**Issue by siyuch-fdu** [VIPriors/vipriors-challenges-toolkit#47]
Hi, organizers:
     In order to avoid disputes, please clarify the DDL of the technical report. Is it 23:59 UTC, October 1st or other time? Is this the ddl for sending emails or the ddl for uploading arxiv files?

**Comment by rjbruin** [comment]
Yes, this is the deadline by which we should have received an email with a link to a public arXiv entry.

**Comment by luan-g** [comment]
@rjbruin Is it available to send an email with the report before the deadline?

**Comment by rjbruin** [comment]
Yes, please email your tech report to us.
