### ISSUE TITLE
Technical report issue

### ISSUE THREAD

**Issue by keloee** [VIPriors/vipriors-challenges-toolkit#48]
I'm a participant of the action recognition track, I have a few ment for the tec report. 1. Is there any template for technical report? 2. For verification, the ddl is October 1st 23:59 GMT, and we can send the report directly to vipriors-ewi@tudelft.nl?

**Comment by LcenArthas** [comment]
By the way, I would like to ask, is there any other information that needs to be given in the email for submitting the report? For example, team members, team members’s organization and other information？

**Comment by rjbruin** [comment]
There is no template for the tech report The deadline is correct, and the email address too.

We do need to know the names of the team members and the organization.
