### ISSUE TITLE
Question about the poster session

### ISSUE THREAD

**Issue by siyuch-fdu** [VIPriors/vipriors-challenges-toolkit#49]
Hi organizers,
     I have noticed that all accepted works will be presented on ICCV gatherly in the poster session. Do the winning teams of the challenge need to provide posters?

**Comment by rjbruin** [comment]
We had not originally planned for this, but we're looking into arranging this. Note though that the workshop is today at 19h CEST, and that ICCV registration is required to attend. Can you please confirm if you would be able to make it in that case?

**Comment by rjbruin** [comment]
Unfortunately the ICCV organizers are not able to arrange this at this moment. We're sorry we didn't think of this before.
