### ISSUE TITLE
When will the 2022 challenge codalab open?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [VIPriors/vipriors-challenges-toolkit#53]

**Comment by rjbruin** [comment]
Thanks for your interest! We are hard at work at releasing the challenges. We expect to open them soon.

**Comment by Icecream-blue-sky** [comment]
Very much looking forward to the opening of the challenge!

**Comment by rjbruin** [comment]
Hi @Icecream-blue-sky, the challenges are now open! Sorry for the delay.

See information here: https://vipriors.github.io/challenges/
