### ISSUE TITLE
No updates can be seen in 2022

### ISSUE THREAD

**Issue by LUJUNYIhhh** [VIPriors/vipriors-challenges-toolkit#54]
Hi, I would like to ask whether the data would be updated or not. Are we going to use the same data in last year? The website on Codalab was also not updated yet. Where shell we sign in for the challenge? Besides, we also want to ask the final evaluation criterion is AP@0.5:0.95 just like coco or criterion in the DelftBikes paper HALLUCINATION IN OBJECT DETECTION — A STUDY IN VISUAL PART VERIFICATION? Thankyou.

**Comment by llf10811020205** [comment]
mark

**Comment by rjbruin** [comment]
Thanks for your interest! We are working hard to open the challenges as soon as possible. Your questions should be answered then. Please stay tuned!

**Comment by LUJUNYIhhh** [comment]
Thanks a lot !

**Comment by rjbruin** [comment]
Hi @LUJUNYIhhh, the challenges are now open! Sorry for the delays.

See information here: https://vipriors.github.io/challenges/
