### ISSUE TITLE
Imagenet dataset too large to download

### ISSUE THREAD

**Issue by Viswesh-N** [VIPriors/vipriors-challenges-toolkit#57]
Running the generate_images.py requires one to download the full Imagenet 2012 dataset, which is quite large. Is there any chance a drive link can be provided which contains the subset of the dataset with which we are expected to work with?

**Comment by rjbruin** [comment]
Hi Viswesh, I understand the concern, however, we do not own ImageNet, so we don't have the rights to distribute the images ourselves. Sorry!
