### ISSUE TITLE
Image Classification -- Question about the Datatset

### ISSUE THREAD

**Issue by BaoliangChen-stu** [VIPriors/vipriors-challenges-toolkit#60]
Dear Professor:

We have a queation about the dataset in training stage.

1. We are not allowed to train our model on original ImageNet-2012 validation data. 
2. Can we train our model on the generated training and validation data? 

Are the above two understandings right?

Thanks for your time!

**Comment by rjbruin** [comment]
Hi,

1. You are correct. No other data than the provided data can be used.
2. The data that you generate using the toolkit, which is a subset of ImageNet, is the only correct data to use.

**Comment by yashika-git** [comment]
Hi @rjbruin,

Will it be possible for you (the organizers) to provide access to the subset of Imagenet dataset which is to be used for training of Image Classification Challenge?
Actually, my teammates and I are unable to download the complete Imagenet Dataset on our local systems.
So, it would be really helpful if access to just the subset could be provided.

Thank You

**Comment by rjbruin** [comment]
Hi @yashika-git, unfortunately we cannot provide the data ourselves, as we do not have the rights to distribute the data. I hope you can find a way to access the dataset.
