### ISSUE TITLE
 Action Recognition Challenge Sever

### ISSUE THREAD

**Issue by Jmh0527** [VIPriors/vipriors-challenges-toolkit#61]
I used the chance.py you provided to randomly generate the .txt file and compress it to .zip, but the commit on sever failed. Why is this?
![image](https://user-images.githubusercontent.com/97495534/184539896-d6b24736-3f70-4172-aace-21fcee371adc.png)
![image](https://user-images.githubusercontent.com/97495534/184540034-fb395797-a94c-42af-9c4d-bd2bd99fb334.png)

**Comment by bapmbr** [comment]
We are checking this!

**Comment by Jmh0527** [comment]
> We are checking this!

Thank you for your reply. I found the error prompt on the server that the upload should set the file name to 'submission.txt'.
