### ISSUE TITLE
The Email address of the recipient does not exist, or is temporarily unavailable.

### ISSUE THREAD

**Issue by YJingyu** [VIPriors/vipriors-challenges-toolkit#66]
When I send the email to 【vipriors-ewi@tudelft.nl】, it failed, and the feedback is【I'm sorry your email is returned, the related information for this message: The Email address of the recipient does not exist, or is temporarily unavailable.】, can you check the email address?
@rjbruin @Attila94

**Comment by rjbruin** [comment]
Hi @YJingyu, are you sure you used the right email address? We have been received emails on that exact email address for the last 24 hours.

**Comment by ymzhu385** [comment]
Hello, would you reply the technical report email if it received successfully?
@rjbruin

**Comment by YJingyu** [comment]
> Hi @YJingyu, are you sure you used the right email address? We have been received emails on that exact email address for the last 24 hours.

Maybe my attachment is too large, I will compress it and send again

**Comment by rjbruin** [comment]
Hi, can you tell us your email address? Or else the exact contents of your email? We are receiving a lot of emails today, because of the impending deadline.
