### ISSUE TITLE
Data annotation

### ISSUE THREAD

**Issue by Treeboy2762** [VIPriors/vipriors-challenges-toolkit#68]
Is it possible to produce extra annotation for the training data?

Thanks.

**Comment by rjbruin** [comment]
Hi,

Do you mean if we can provide more annotations? Or if it is allowed to create more annotations on the training data yourself?

You can use the training data in any way you like, including changing the annotations.

**Comment by Treeboy2762** [comment]
I meant if we could modify the annotations ourselves. Thank you for your answer!
