### ISSUE TITLE
Can we use testing data as unlabeled data in training?

### ISSUE THREAD

**Issue by DAVEISHAN** [VIPriors/vipriors-challenges-toolkit#7]
Hello, 

I am interested in VIPriors challenge. I am curious to know if I can use testing data as unlabeled data and include in my training. 

Let me know soon.

-Ishan

**Comment by rjbruin** [comment]
Hi Ishan,

Thanks for your interest in our workshop! We do not allow using the test data to train the model. The test data should not be observed by the model to ensure fair evaluation.

With regards,
Robert-Jan


Op 19 jun. 2020 21:45 schreef DAVEISHAN <notifications@github.com>:

Hello,

I am interested in VIPriors challenge. I am curious to know if I can use testing data as unlabeled data and include in my training.

Let me know soon.

-Ishan
